# -*- coding: utf-8 -*-
"""Cassidoo_Interview_Question_June_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gawGKGzlzDF1W0srCMlEIWsLWkx5WpDu
"""

# Recursive Code
# Time Complexity: O(n)
# Space Complexity: O(n)

def nest_array_recursive(input_array):
  if not input_array:
    return []
  if len(input_array) == 1:
    return input_array
  return [input_array[0]] + [nest_array_recursive(input_array[1:])]

nest_array_recursive([1, 2, 3, 4, 5, 6, 7, 8])

nest_array_recursive([])

# Iterative Code
# Time Complexity: O(n)
# Space Complexity: O(n)

def nest_array_iterative(input_array):
  if not input_array:
    return []
  result = [input_array[-1]]
  for i in range(len(input_array) - 2, -1, -1):
   result = [input_array[i], result]
  return result

nest_array_iterative([1, 2, 3, 4, 5, 6, 7, 8])

nest_array_iterative([])